/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_CD9C402F_B072_4D54_8916_DC1848345E8E</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_CD9C402F_B072_4D54_8916_DC1848345E8E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_CD9C402F_B072_4D54_8916_DC1848345E8E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
